### ISSUE TITLE
Registros duplicados

### ISSUE THREAD

**Issue by 8devmx** [8devmx/modelos-de-bd-primer-parcial#28]
Como usuario de sistema, no se deberán de permitir registros duplicados

### Requerimientos

1.  Utilizar llaves únicas
2. Utilizar insert ignore into

![image](https://github.com/8devmx/modelos-de-bd-primer-parcial/assets/118553883/742d0656-24a9-45cd-b43e-565a174b6876)

**Comment by Ramiro440** [comment]
Se cierra issue quedo al 100 esta parte.
